services:
    postgres:
        image: postgres:latest
        container_name: arkhon-db
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        env_file:
            - .env
        ports:
            - '5432:5432'
        volumes:
            - ./pgdata:/var/lib/postgresql/data
